urdf: "urdf/xhand_right.urdf"
sub_topic: joint_cmd
pub_topic: joint_states
# init_q:
#   right_shoulder_pitch_joint: 0
#   right_shoulder_roll_joint: 0
#   right_shoulder_yaw_joint: 0
#   right_elbow_joint: 0
#   right_wrist_roll_joint: 0
#   right_wrist_pitch_joint: 0
#   right_wrist_yaw_joint: 0
#   left_shoulder_pitch_joint: 0
#   left_shoulder_roll_joint: 0
#   left_shoulder_yaw_joint: 0
#   left_elbow_joint: 0
#   left_wrist_roll_joint: 0
#   left_wrist_pitch_joint: 0
#   left_wrist_yaw_joint: 0
# fixed_link: "torso_link"